export const EXPAND_NAVBAR = 'EXPAND_NAVBAR';
export const COLLAPSE_NAVBAR = 'COLLAPSE_NAVBAR';

export const EXPAND_USER_DROPDOWN = 'EXPAND_USER_DROPDOWN';
export const COLLAPSE_USER_DROPDOWN = 'COLLAPSE_USER_DROPDOWN';